// Mock data and helper for all Facebook Clone profiles
export const allMockUsers = [
  {
    id: 'sumon-roy',
    full_name: 'Sumon Roy',
    first_name: 'Sumon',
    last_name: 'Roy',
    avatar_url: '/images/sumon-profile-icon.jpg',
    cover_url: '/images/Friends-Post/bisu.jpg',
    bio: 'Software Engineer & Tech Enthusiast 💻 | Life is good ✨',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Dinajpur, Bangladesh',
    work: 'Software Developer',
    education: 'Studied Computer Science',
    joined: 'Joined October 2021',
    friends_count: 1420,
    photos: [
      '/images/sumon-profile-icon.jpg',
      '/images/Friends-Post/bisu.jpg',
      '/images/Friends-Post/dipu.jpg',
      '/images/Friends-Post/niloy.jpg',
      '/images/current-world.jpg',
      '/images/deep-heart.jpg',
    ],
  },
  {
    id: 'bisu',
    full_name: 'Bisuu ʚíɞ',
    first_name: 'Bisu',
    last_name: 'Roy',
    avatar_url: '/images/Friends/bisu.jpg',
    cover_url: '/images/Friends-Post/bisu.jpg',
    bio: 'Living my best life ✨ Traveling & Photography lover 📸',
    lives_in: 'Rangpur, Bangladesh',
    from: 'Nilphamari, Bangladesh',
    work: 'Photographer',
    education: 'University of Dhaka',
    joined: 'Joined January 2020',
    friends_count: 856,
    photos: [
      '/images/Friends/bisu.jpg',
      '/images/Friends-Post/bisu.jpg',
      '/images/Friends/joydev.jpg',
      '/images/Friends/dipu.jpg',
    ],
  },
  {
    id: 'dipu',
    full_name: 'Dipu Roy Plabon',
    first_name: 'Dipu',
    last_name: 'Roy',
    avatar_url: '/images/Friends/dipu.jpg',
    cover_url: '/images/Friends-Post/dipu.jpg',
    bio: 'Always stay positive and keep learning 🚀',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Panchagarh, Bangladesh',
    work: 'Digital Marketer',
    education: 'Dhaka College',
    joined: 'Joined March 2019',
    friends_count: 1120,
    photos: [
      '/images/Friends/dipu.jpg',
      '/images/Friends-Post/dipu.jpg',
      '/images/Friends/touhid.jpg',
      '/images/Friends/uttom.jpg',
    ],
  },
  {
    id: 'niloy',
    full_name: 'Niloy Roy',
    first_name: 'Niloy',
    last_name: 'Roy',
    avatar_url: '/images/Friends/niloy.jpg',
    cover_url: '/images/Friends-Post/niloy.jpg',
    bio: 'Coding is art 🎨 Foodie & Gamer 🎮',
    lives_in: 'Chittagong, Bangladesh',
    from: 'Rangpur, Bangladesh',
    work: 'Frontend Developer',
    education: 'BUET',
    joined: 'Joined July 2022',
    friends_count: 630,
    photos: [
      '/images/Friends/niloy.jpg',
      '/images/Friends-Post/niloy.jpg',
      '/images/chess.png',
      '/images/ludo.png',
    ],
  },
  {
    id: 'touhid',
    full_name: 'Touhid Hasan',
    first_name: 'Touhid',
    last_name: 'Hasan',
    avatar_url: '/images/Friends/touhid.jpg',
    cover_url: '/images/Friends-Post/touhud.jpg',
    bio: 'Dream big, work hard, stay humble 🙌',
    lives_in: 'Sylhet, Bangladesh',
    from: 'Sylhet, Bangladesh',
    work: 'Graphic Designer',
    education: 'Shahjalal University',
    joined: 'Joined September 2021',
    friends_count: 940,
    photos: ['/images/Friends/touhid.jpg', '/images/Friends-Post/touhud.jpg'],
  },
  {
    id: 'uttom',
    full_name: 'Uttom Roy',
    first_name: 'Uttom',
    last_name: 'Roy',
    avatar_url: '/images/Friends/uttom.jpg',
    cover_url: '/images/Friends-Post/bisu.jpg',
    bio: 'Music is life 🎵 Violinist & Explorer',
    lives_in: 'Rajshahi, Bangladesh',
    from: 'Dinajpur, Bangladesh',
    work: 'Musician',
    education: 'Rajshahi University',
    joined: 'Joined May 2018',
    friends_count: 1540,
    photos: ['/images/Friends/uttom.jpg', '/images/Friends/emamul.jpg'],
  },
  {
    id: 'joydev',
    full_name: 'Joydev Roy',
    first_name: 'Joydev',
    last_name: 'Roy',
    avatar_url: '/images/Friends/joydev.jpg',
    cover_url: '/images/Friends-Post/dipu.jpg',
    bio: 'Simple living, high thinking 🌸',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Khulna, Bangladesh',
    work: 'Content Creator',
    education: 'Jahangirnagar University',
    joined: 'Joined August 2020',
    friends_count: 780,
    photos: ['/images/Friends/joydev.jpg'],
  },
  {
    id: 'emamul',
    full_name: 'Emamul Haque Emon',
    first_name: 'Emamul',
    last_name: 'Haque',
    avatar_url: '/images/Friends/emamul.jpg',
    cover_url: '/images/Friends-Post/niloy.jpg',
    bio: 'Fitness Enthusiast 💪 Calisthenics lover',
    lives_in: 'Barisal, Bangladesh',
    from: 'Barisal, Bangladesh',
    work: 'Fitness Coach',
    education: 'National University',
    joined: 'Joined November 2021',
    friends_count: 490,
    photos: ['/images/Friends/emamul.jpg'],
  },
  {
    id: 'bejoy',
    full_name: 'Sk Sanju (Bejoy)',
    first_name: 'Sanju',
    last_name: 'Bejoy',
    avatar_url: '/images/Friends/bejoy.jpg',
    cover_url: '/images/Friends-Post/bisu.jpg',
    bio: 'Cricket fan 🏏 & Cinephile 🎬',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Dhaka, Bangladesh',
    work: 'Video Editor',
    education: 'North South University',
    joined: 'Joined February 2023',
    friends_count: 320,
    photos: ['/images/Friends/bejoy.jpg'],
  },
  {
    id: 'wasius',
    full_name: 'Abu Wasius Shahid',
    first_name: 'Abu Wasius',
    last_name: 'Shahid',
    avatar_url: '/images/Friends/wasius.jpg',
    cover_url: '/images/Friends-Post/dipu.jpg',
    bio: 'Books, Coffee & Solitude ☕📖',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Comilla, Bangladesh',
    work: 'Writer & Journalist',
    education: 'BRAC University',
    joined: 'Joined April 2020',
    friends_count: 670,
    photos: ['/images/Friends/wasius.jpg'],
  },
  {
    id: 'atique',
    full_name: 'Atique Shahriar',
    first_name: 'Atique',
    last_name: 'Shahriar',
    avatar_url: '/images/Friends/atique.jpg',
    cover_url: '/images/Friends-Post/touhud.jpg',
    bio: 'Entrepreneur & Tech Geek ⚡',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Dhaka, Bangladesh',
    work: 'Founder at TechStart',
    education: 'AIUB',
    joined: 'Joined June 2019',
    friends_count: 1890,
    photos: ['/images/Friends/atique.jpg'],
  },
  {
    id: 'norry',
    full_name: 'Nusrat Norry',
    first_name: 'Nusrat',
    last_name: 'Norry',
    avatar_url: '/images/Friends/norry.jpg',
    cover_url: '/images/Friends-Post/niloy.jpg',
    bio: 'Fashion, Makeup & Lifestyle 💄👗',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Chittagong, Bangladesh',
    work: 'Model & Influencer',
    education: 'IUB',
    joined: 'Joined December 2022',
    friends_count: 2450,
    photos: ['/images/Friends/norry.jpg'],
  },
  {
    id: 'sraboni',
    full_name: 'Sraboni Aktar',
    first_name: 'Sraboni',
    last_name: 'Aktar',
    avatar_url: '/images/Friends/sraboni.jpg',
    cover_url: '/images/Friends-Post/bisu.jpg',
    bio: 'Passionate about painting & art 🎨🖌️',
    lives_in: 'Khulna, Bangladesh',
    from: 'Khulna, Bangladesh',
    work: 'Artist',
    education: 'Charukala Institute',
    joined: 'Joined January 2021',
    friends_count: 980,
    photos: ['/images/Friends/sraboni.jpg'],
  },
  {
    id: 'nabil',
    full_name: 'Nabil Al Tamash',
    first_name: 'Nabil',
    last_name: 'Al Tamash',
    avatar_url: '/images/Friends/nabil.jpg',
    cover_url: '/images/Friends-Post/dipu.jpg',
    bio: 'Cybersecurity Analyst 🛡️ | Hacker Mindset 💻',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Rajshahi, Bangladesh',
    work: 'Security Engineer',
    education: 'DIU',
    joined: 'Joined August 2021',
    friends_count: 540,
    photos: ['/images/Friends/nabil.jpg'],
  },
  {
    id: 'nahid',
    full_name: 'Nahid Rahman',
    first_name: 'Nahid',
    last_name: 'Rahman',
    avatar_url: '/images/Friends/nahid.jpg',
    cover_url: '/images/Friends-Post/niloy.jpg',
    bio: 'Full Stack Dev | React & Node ⚡',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Sylhet, Bangladesh',
    work: 'Software Architect',
    education: 'SUST',
    joined: 'Joined October 2019',
    friends_count: 1320,
    photos: ['/images/Friends/nahid.jpg'],
  },
  {
    id: 'sujon',
    full_name: 'Sujon Roy',
    first_name: 'Sujon',
    last_name: 'Roy',
    avatar_url: '/images/Friends/sujon.jpg',
    cover_url: '/images/Friends-Post/touhud.jpg',
    bio: 'Always learning new things! 🌟',
    lives_in: 'Mymensingh, Bangladesh',
    from: 'Dinajpur, Bangladesh',
    work: 'Banker',
    education: 'Mymensingh College',
    joined: 'Joined March 2022',
    friends_count: 430,
    photos: ['/images/Friends/sujon.jpg'],
  },
];

// Helper to find profile by ID or partial match
export function getMockProfile(id) {
  if (!id) return allMockUsers[0];
  const found = allMockUsers.find(
    (u) =>
      u.id === id ||
      u.id.toLowerCase().includes(id.toLowerCase()) ||
      u.full_name.toLowerCase().includes(id.toLowerCase())
  );
  if (found) return found;

  // Fallback dynamic profile
  return {
    id,
    full_name: id.replace(/[-_]/g, ' '),
    first_name: id.split(/[-_ ]/)[0] || 'User',
    last_name: '',
    avatar_url: '/images/sumon-profile-icon.jpg',
    cover_url: '/images/Friends-Post/bisu.jpg',
    bio: 'Welcome to my Facebook profile!',
    lives_in: 'Dhaka, Bangladesh',
    from: 'Bangladesh',
    work: 'Member at Facebook',
    education: 'High School',
    joined: 'Joined Recently',
    friends_count: 120,
    photos: ['/images/sumon-profile-icon.jpg'],
  };
}

// People You May Know list
export const friendSuggestions = allMockUsers.slice(3, 11).map((u, i) => ({
  id: u.id,
  name: u.full_name,
  avatar: u.avatar_url,
  mutual: `${2 + (i % 5)} mutual friends`,
}));
